<?xml>
<xs:schema>
  <xs:element name="StaffList">
    <xs:complexType>
        <xs:element name="Staff">
          <xs:complexType>
              <xs:element name="ID" type="xs:string"/>
              <xs:element name="Position">
                <xs:complexType>
                    <xs:element name="Title" type="xs:string"/>
                    <xs:element name="Responsibility" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Salary">
                <xs:complexType>
                    <xs:element name="PartTime" type="xs:string"/>
                    <xs:element name="FullTime" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Department">
                <xs:complexType>
                    <xs:element name="Name" type="xs:string"/>
                    <xs:element name="DeskNo" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="DateJoined" type="xs:date"/>
          </xs:complexType>
        </xs:element>
    </xs:complexType>
  </xs:element>

</xs:schema>
